app/blog/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, HiddenField, BooleanField, TextAreaField
from wtforms.validators import DataRequired

class CreateBlogPostForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired()])
    content = TextAreaField("Content", validators=[DataRequired()], render_kw={"rows": 20})
    content_preview = TextAreaField("Content Preview", validators=[DataRequired()], render_kw={"rows": 6})
    publish = BooleanField("Publish?")
    submit = SubmitField("Create Post")

app/blog/__init__.py
from flask import Blueprint

bp = Blueprint("blog", __name__)

from app.blog import routes

app/blog/routes.py
from flask import render_template, flash, redirect, url_for, request, session
from flask_login import current_user, login_required
from app import db
from app.models import BlogPost
from app.blog import bp
from app.blog.forms import CreateBlogPostForm
import re

@bp.route("/")
@bp.route("/index")
def index():
    published_posts = BlogPost.query.filter_by(is_published=True).order_by(BlogPost.id.desc()).all()
    
    return render_template("blog/index.html", title="Blog", published_posts=published_posts)


@bp.route("/create", methods=["GET", "POST"])
@login_required
def create():
    # Only let authorised blog authors create posts
    if not current_user.is_blog_author:
        return redirect(url_for("blog.index"))

    form = CreateBlogPostForm()

    # For a post
    if form.validate_on_submit():
        slug = re.sub("[^\w]+", "-", form.title.data.lower())
        new_post = BlogPost(author=current_user,
                            title=form.title.data,
                            slug=slug,
                            content=form.content.data,
                            content_preview=form.content_preview.data,
                            is_published=form.publish.data)

        db.session.add(new_post)
        db.session.commit()

        return redirect(url_for("blog.drafts"))

    return render_template("blog/create.html", title="Create Blog Post", form=form)


@bp.route("/<slug>")
def view_post(slug):
    blog_post = BlogPost.query.filter_by(slug=slug).first_or_404()

    if (not blog_post.is_published) and (not current_user.is_blog_author):
        return redirect(url_for("blog.index"))

    return render_template("blog/view_post.html", title=blog_post.title, blog_post=blog_post)


@bp.route("/drafts")
@login_required
def drafts():
    # Only let authorised blog authors see drafts
    if not current_user.is_blog_author:
        return redirect(url_for("blog.index"))

    draft_posts = BlogPost.query.filter_by(is_published=False).all()

    return render_template("blog/drafts.html", title="Draft Blog Posts", draft_posts=draft_posts)


@bp.route("/delete_post/<id>")
@login_required
def delete_post(id):
    # Only let authorised blog authors see drafts
    if not current_user.is_blog_author:
        return redirect(url_for("blog.index"))

    blog_post = BlogPost.query.get(int(id))
    flash("Deleted blog post {title}".format(title=blog_post.title))
    db.session.delete(blog_post)
    db.session.commit()

    return redirect(url_for("blog.drafts"))


@bp.route("/publish_post/<id>")
@login_required
def publish_post(id):
    # Only let authorised blog authors see drafts
    if not current_user.is_blog_author:
        return redirect(url_for("blog.index"))

    blog_post = BlogPost.query.get(int(id))
    blog_post.is_published = True

    flash("Published {title}".format(title=blog_post.title))
    db.session.commit()

    return redirect(url_for("blog.index"))

app/templates/blog/create.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block app_content %}
	<h2>Create Blog Post</h2>
	<div class="row">
		<div class="col-md-10">
			{{ wtf.quick_form(form) }}
		</div>
	</div>
{% endblock %}

app/templates/blog/drafts.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block styles %}
    {{ super() }}
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Nunito" />

    <style>        
        @media (min-width: 992px) { .container { max-width: 968px; } }

        #blog-container {
            font-family: "Nunito";
        }
    </style>
{% endblock %}



{% block app_content %}
    <div id="blog-container">
        <h2>Draft Blog Posts</h2>
        {% for blog_post in draft_posts %}
            <hr/>
            <h3><a href="{{ url_for('blog.view_post', slug=blog_post.slug) }}">{{ blog_post.title }}</a></h3>
            <p><i>By {{ blog_post.author.display_name }} on {{ blog_post.created_date }}</i></p>
            {{ blog_post.html_content_preview }}
            <div class="mt-4">
                <a class="btn btn-primary" role="button" href="{{ url_for('blog.publish_post', id=blog_post.id) }}">Publish</a>
                <a class="btn btn-secondary" role="button" href="{{ url_for('blog.delete_post', id=blog_post.id) }}">Delete</a>
            </div>
        {% endfor %}
    </div>
{% endblock %}

app/templates/blog/index.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block app_content %}
    <h2>The Blog!</h1>
{% endblock %}

app/templates/blog/view_post.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block styles %}
    {{ super() }}
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Nunito" />

    <style>        
        @media (min-width: 992px) { .container { max-width: 968px; } }

        #blog-container {
            font-family: "Nunito";
        }
    </style>
{% endblock %}

{% block app_content %}
    <div id="blog-container">
        <h2>{{ blog_post.title }}</h2>
        <p><i>By {{ blog_post.author.display_name }} on {{ blog_post.created_date }}</i></p>
        {{ blog_post.html_content }}
        [<a href="{{ url_for('blog.index') }}">Back to Blog Home</a>]
    </div>
{% endblock %}